
package cz.cvut.sep.rychljir.customerDatabase;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerDatabase", targetNamespace = "http://www.cvut.cz/FEL/", wsdlLocation = "file:/E:/\u0160kola/VS/MGR3/SEP/semestralka/CustomerDatabase.wsdl")
public class CustomerDatabase
    extends Service
{

    private final static URL CUSTOMERDATABASE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERDATABASE_EXCEPTION;
    private final static QName CUSTOMERDATABASE_QNAME = new QName("http://www.cvut.cz/FEL/", "CustomerDatabase");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/\u0160kola/VS/MGR3/SEP/semestralka/CustomerDatabase.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERDATABASE_WSDL_LOCATION = url;
        CUSTOMERDATABASE_EXCEPTION = e;
    }

    public CustomerDatabase() {
        super(__getWsdlLocation(), CUSTOMERDATABASE_QNAME);
    }

    public CustomerDatabase(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERDATABASE_QNAME, features);
    }

    public CustomerDatabase(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERDATABASE_QNAME);
    }

    public CustomerDatabase(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERDATABASE_QNAME, features);
    }

    public CustomerDatabase(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerDatabase(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerDatabaseWSDL
     */
    @WebEndpoint(name = "CustomerDatabaseSOAP")
    public CustomerDatabaseWSDL getCustomerDatabaseSOAP() {
        return super.getPort(new QName("http://www.cvut.cz/FEL/", "CustomerDatabaseSOAP"), CustomerDatabaseWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerDatabaseWSDL
     */
    @WebEndpoint(name = "CustomerDatabaseSOAP")
    public CustomerDatabaseWSDL getCustomerDatabaseSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cvut.cz/FEL/", "CustomerDatabaseSOAP"), CustomerDatabaseWSDL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERDATABASE_EXCEPTION!= null) {
            throw CUSTOMERDATABASE_EXCEPTION;
        }
        return CUSTOMERDATABASE_WSDL_LOCATION;
    }

}
