
package cz.cvut.sep.rychljir.customerDatabase;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerDatabaseWSDL", targetNamespace = "http://www.cvut.cz/FEL/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerDatabaseWSDL {


    /**
     * 
     * @param count
     * @param from
     * @return
     *     returns java.util.List<cz.cvut.sep.rychljir.customerDatabase.CustomerType>
     */
    @WebMethod(operationName = "ReadAllCustomers", action = "http://www.cvut.cz/FEL/ReadAllCustomers")
    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "ReadAllCustomers", targetNamespace = "http://www.cvut.cz/FEL/", className = "cz.cvut.sep.rychljir.customerDatabase.ReadAllCustomers")
    @ResponseWrapper(localName = "ReadAllCustomersResponse1", targetNamespace = "http://www.cvut.cz/FEL/", className = "cz.cvut.sep.rychljir.customerDatabase.ReadAllCustomersResponse1")
    public List<CustomerType> readAllCustomers(
        @WebParam(name = "from", targetNamespace = "")
        BigInteger from,
        @WebParam(name = "count", targetNamespace = "")
        BigInteger count);

    /**
     * 
     * @param id
     * @param status
     * @param customer
     */
    @WebMethod(operationName = "ReadCustomerDetails", action = "http://www.cvut.cz/FEL/ReadCustomerDetails")
    @RequestWrapper(localName = "ReadCustomerDetails", targetNamespace = "http://www.cvut.cz/FEL/", className = "cz.cvut.sep.rychljir.customerDatabase.ReadCustomerDetails")
    @ResponseWrapper(localName = "ReadCustomerDetailsResponse1", targetNamespace = "http://www.cvut.cz/FEL/", className = "cz.cvut.sep.rychljir.customerDatabase.ReadCustomerDetailsResponse1")
    public void readCustomerDetails(
        @WebParam(name = "id", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<BigInteger> id,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> status,
        @WebParam(name = "customer", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<CustomerDetailType> customer);

    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "CreateCustomerChangeOrder", action = "http://www.cvut.cz/FEL/CreateCustomerChangeOrder")
    @WebResult(name = "CreateCustomerChangeOrderResponse1", targetNamespace = "http://www.cvut.cz/FEL/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public Object createCustomerChangeOrder(
        @WebParam(name = "CreateCustomerChangeOrder", targetNamespace = "http://www.cvut.cz/FEL/", partName = "parameters")
        CreateCustomerChangeOrder parameters);

}
