
package cz.cvut.sep.rychljir.ws.time;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-23T19:16:09.798+01:00
 * Generated source version: 3.1.8
 * 
 */
public final class TimeUtilService_TimeUtilPort_Client {

    private static final QName SERVICE_NAME = new QName("http://profinit.eu/time/util/", "TimeUtilService");

    private TimeUtilService_TimeUtilPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TimeUtilService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TimeUtilService_Service ss = new TimeUtilService_Service(wsdlURL, SERVICE_NAME);
        TimeUtilService port = ss.getTimeUtilPort();  
        
        {
        System.out.println("Invoking getDate...");
        boolean _getDate_returnException = false;
        try {
            java.lang.String _getDate__return = port.getDate(_getDate_returnException);
            System.out.println("getDate.result=" + _getDate__return);

        } catch (TimeUtilException_Exception e) { 
            System.out.println("Expected exception: TimeUtilException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
