
package cz.cvut.sep.rychljir.ws.time;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-23T19:16:09.866+01:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "TimeUtilException", targetNamespace = "http://profinit.eu/time/util/")
public class TimeUtilException_Exception extends Exception {
    
    private TimeUtilException timeUtilException;

    public TimeUtilException_Exception() {
        super();
    }
    
    public TimeUtilException_Exception(String message) {
        super(message);
    }
    
    public TimeUtilException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TimeUtilException_Exception(String message, TimeUtilException timeUtilException) {
        super(message);
        this.timeUtilException = timeUtilException;
    }

    public TimeUtilException_Exception(String message, TimeUtilException timeUtilException, Throwable cause) {
        super(message, cause);
        this.timeUtilException = timeUtilException;
    }

    public TimeUtilException getFaultInfo() {
        return this.timeUtilException;
    }
}
